### PR TITLE
Update urls and version in package.json

### PR DESCRIPTION
**Pull request by will-moore**
Update package.json as suggested https://github.com/ome/figure/issues/112 by @joshmoore.

### CODE REVIEW

**Comment by joshmoore** [comment]
WFM. Guess there's just a question of if anything is needed to prevent it becoming out of sync.

**Comment by will-moore** [comment]
@joshmoore I've added "update package.json" to the release list at https://trello.com/c/GXQxBOHe/40-release-tagged-zip-at-downloads-openmicroscopy-org-figure (3rd checkbox).

**Comment by sbesson** [comment]
My naive proposal would be to add a step in the Travis build comparing `python -c "import json; print json.loads(open('package.json').read())['version']"` to `git describe --tags --abbrev=0`.

**Comment by will-moore** [comment]
@sbesson That currently gives me:
```
$ git describe --tags --abbrev=0
v1.1.1
$ python -c "import json; print json.loads(open('package.json').read())['version']"
1.1.1
```
So, the travis build would fail if you update the tag or version independently?
I guess this could be useful.

**Comment by joshmoore** [comment]
> @joshmoore I've added "update package.json" to the release list at https://trello.com/c/GXQxBOHe/40-release-tagged-zip-at-downloads-openmicroscopy-org-figure (3rd checkbox).

"KISS" Certainly a good place to start. I wonder if it's time for a release-template board and having someone else try it out?

**Pull request merged**
