### PR TITLE
Rois from omero

### PR DESCRIPTION
**Pull request by will-moore**
This allows loading of ROIs from OMERO to add to figure panels as new Shapes.

To test:
 - Pick a multi-plane image (also good to test with single plane image)
 - Create a bunch of ROIs with single or multiple shapes of all types using Insight. Include rotated Ellipses.
 - Add that image to OMERO.figure, select it and in the right tab 'ROIs' click "Draw".
 - Test that drawing shapes manually works OK as before.
 - Click "Load ROIs from OMERO"
 - Should see a list of ROIs / shapes, similar to view in webclient with ROIs expandable to show Shapes.
 - Hovering over each Shape row displays it on the image. Clicking on row sets the Z & T of the image to the Z & T of that shape. Clicking "Add" will add the Shape to the image.
 - Click OK to close dialog and save shapes to image panel.
 - Open the "Draw" dialog for a different image to check the dialog is re-rendered correctly.

Discussed with @bramalingam: various things to improve:

 - [x] "Load ROIs" button instead of loading instantly
 - [x] Get bounding box for Ellipse, Line & Rectangle - zoom to show shape within region
 - [x] Collapse shapes under ROI by default (as in webclient & crop dialog)
 - [x] Clicking on shape updates Z/T to that plane (as in webclient) but we don't save Z/T yet.
 - [x] Clicking on "Add Shape" adds shape to viewer and selects it. We save this Z/T.
 - [x] Divergence of shape-editor model and OMERO model. E.g. ellipse cx, cy, rx, ry -> x, y, radiusX, radiusY. Do we update shape-editor to use new model? If so then we need to update existing OMERO.figure files when opened. BUT still need to handle pre OMERO 5.3 with older model.

Follow up ideas:
 - Render all shapes if number of planes is small (10 or less)
 - Maybe option to filter shapes by current plane?
 - When Ellipses are added, x, y, rx, ry are recalculated from handles (to handle transforms) but this means that they are not detected as duplicates
 - Maybe add Z & T sliders?
 - Maybe show shapes on viewer when mouseover area!? - click to add?!
 - Do we allow shape to be added if previously added & moved? Don't want duplicate IDs!
 - Zoom out of preview to show shape in context? Make line thicker to improve visibility?

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#217](https://ci.openmicroscopy.org/job/FIGURE-merge/217/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/217/consoleText) for more details.
Possible conflicts:
  - PR #152 will-moore 'open with images'
    - static/figure/figure.js
  - PR #158 dominikl 'Label markdown'
    - static/figure/figure.js
  - PR #160 will-moore 'Luts'
    - static/figure/figure.js
  - PR #162 dominikl 'Import from json'
    - static/figure/figure.js
  - Upstream changes
    - static/figure/figure.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#218](https://ci.openmicroscopy.org/job/FIGURE-merge/218/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/218/consoleText) for more details.
Possible conflicts:
  - PR #158 dominikl 'Label markdown'
    - static/figure/figure.js
  - PR #160 will-moore 'Luts'
    - static/figure/figure.js
  - PR #162 dominikl 'Import from json'
    - static/figure/figure.js
  - Upstream changes
    - static/figure/figure.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#219](https://ci.openmicroscopy.org/job/FIGURE-merge/219/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/219/consoleText) for more details.
Possible conflicts:
  - PR #158 dominikl 'Label markdown'
    - static/figure/figure.js
  - PR #160 will-moore 'Luts'
    - static/figure/figure.js
  - PR #162 dominikl 'Import from json'
    - static/figure/figure.js
  - Upstream changes
    - static/figure/figure.js

**Comment by will-moore** [comment]
@bramalingam This is mostly done now and is available on cowfish for testing if you'd like to have a preliminary look? Cheers.
Currently I don't limit the loading of planes (just load them all as needed).

**Comment by pwalczysko** [comment]
Bug: Ellipse drawing in Figure itself (not the ROIs imported from omero) from scratch does not work (the ellipse is drawn without lines, with the markers only)
screen shot 2016-08-22 at 15 33 41

**Comment by pwalczysko** [comment]
If you click onto the green button in the dialogue in screenshot below and the image has NO ROIs to import from omero, then you are confronted with an empty white pane (the right-hand pane), i.e. both the button and the Tip vanish without explanation.
screen shot 2016-08-22 at 15 34 52

**Comment by pwalczysko** [comment]
Clarify the situation with multipoint line. Note, that this type of ROI comes out of ellipses done via ImageJ and our plugin, but it is NOT supported by Figure.
I would suggest it should be supported.

**Comment by pwalczysko** [comment]
As discussed, the Shapes which are not supported by Figure (e.g. points, polylines as mentioned in  https://github.com/ome/figure/pull/165#issuecomment-241433550 etc. ) should still be listed in the list of ROIs to Add to the image in Figure. This is so as not to confuse the user about "Where are my ROIs which I have drawn in OMERO ?"

screen shot 2016-08-22 at 15 39 44

**Comment by will-moore** [comment]
@pwalczysko Addressed most of your comments:
 - "Load ROIs from OMERO" button disabled if image has no ROIs.
 - Fixed drawing of Ellipses by hand
 - Show unsupported types in list of ROIs from OMERO. Tooltip says "Point not supported in OMERO.figure":

screen shot 2016-08-23 at 13 37 26

 - Adding of PolyLine support to OMERO.figure is outside the scope of this PR.

**Comment by will-moore** [comment]
Last 4 commits update the Model that we're using for Shapes to keep in sync with OMERO.
```
Ellipse cx, cy, rx, ry -> x, y, radiusX, radiusY,
```
To test, open a figure that was previously saved with some Ellipses on it.
Also try to load ROIs from OMERO.
Would be good to test against old OMERO (pre 5.3.0) at some point before release.
Also, with https://github.com/ome/figure/pull/162, you should be able to export json from old version and import by pasting into new.

**Comment by jburel** [comment]
The work on ROIs in figure started before the existence of https://github.com/openmicroscopy/omero-marshal
When adding new functionalities,  it will make more sense to start using omero-marshal instead of creating another model since we will have 2 models to maintain/synchronize. This not only doubles the amount of coding but also the amount of testing.
This will obviously require some refactoring and slow down the release of the new functionality but it is preferable in the long run.

omero-marhsal is already used in https://github.com/waxenegger/ome-ol3-viewer.
See https://github.com/waxenegger/ome-ol3-viewer/blob/master/plugin/ome-ol3-viewer/views.py for example.

**Comment by will-moore** [comment]
@jburel All the changes here are dealing with JavaScript data and have nothing to do with converting OMERO model objects to json. We are not creating another model.
When the webgateway api (which uses omero_marshal) gets to supporting ROIs and Shapes then no other clients (webclient, ol3-viewer, figure etc) will have to duplicate the shapeMarshal code.
Currently OMERO.figure uses the shapeMarshal code that's in webgateway to get json data from OMERO (avoiding code duplication). Making OMERO.figure use omero_marshal would mean we implement the same code in multiple places, increasing maintenance and testing, not reducing it.

**Comment by jburel** [comment]
I appreciated that some changes a javascript only, but not all,
and that also in the long term we will be using the new webgateway API.

Major efforts have been made to try to keep figure, version "agnostic".
This is also one of the goals of omero-marshal.

The new API is still under development,
omero-marshal can already be used, evaluated in "real-life" applications e.g. pathviewer, ol3-viewer, figure etc.

Yes in the meantime, it might mean more efforts: we had to do that in other part of the platform.
More importantly we should use the tools/libraries that we develop i.e. eating our own dog food.
This is a good way to make them better e.g. https://github.com/openmicroscopy/omero-marshal/pull/6
Ignoring them in the applications that we develop
sends the wrong message to external wishing to build their own app
and also prevents from showing how one can interact with the various components of the omero-ecosystem.


Rois loaded from omero should be encoded using omero-marshal
then the "rest" will handled the encoded data.

**Comment by pwalczysko** [comment]
Tested the new commits as per https://github.com/ome/figure/pull/165#issuecomment-241716983. All good, also found a Figure with ellipse drawn previously and looked fine.
The only comment:
  - the tooltip telling me that e.g. Point is not supported is popping up only if I hover exactly over the word ``Point`` - it would be more consistent and helpful if hovering on the whole line elicits the tooltip

**Comment by will-moore** [comment]
Also tested "Import from JSON" on cowfish, using JSON exported before the version change above.
Worked fine, created https://cowfish.openmicroscopy.org/webmerge/figure/file/14615. Original version of this figure (not saved to VERSION 2 yet) still opens OK:
https://cowfish.openmicroscopy.org/webmerge/figure/file/14451/

**Pull request closed without merging**
