### PR TITLE
Improve file filter

### PR DESCRIPTION
**Pull request by will-moore**
This improves the filtering of figure files in the File > Open dialog as discussed at https://github.com/ome/figure/issues/146.

To test:
 - Open the File > Open dialog
 - Try filtering the files with multiple words as discussed in https://github.com/ome/figure/issues/146
 - Files should appear in the filtered list if all search words are found in the figure name, regardless of order - splitting words on white-space.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#125](https://ci.openmicroscopy.org/job/FIGURE-merge/125/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/125/consoleText) for more details.
Possible conflicts:
  - PR #145 will-moore 'File open dialog'
    - static/figure/figure.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#126](https://ci.openmicroscopy.org/job/FIGURE-merge/126/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/126/consoleText) for more details.
Possible conflicts:
  - PR #145 will-moore 'File open dialog'
    - static/figure/figure.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#127](https://ci.openmicroscopy.org/job/FIGURE-merge/127/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/127/consoleText) for more details.
Possible conflicts:
  - PR #145 will-moore 'File open dialog'
    - static/figure/figure.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#128](https://ci.openmicroscopy.org/job/FIGURE-merge/128/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/128/consoleText) for more details.
Possible conflicts:
  - PR #145 will-moore 'File open dialog'
    - static/figure/figure.js

**Comment by pwalczysko** [comment]
Works as expected. Tested with the example delivered by the external user in https://github.com/ome/figure/issues/146. Ready to mrege.

**Comment by jburel** [comment]
Will be possible to create a common method instead of having the same code twice?

**Comment by will-moore** [comment]
You're seeing the code changes twice because the concatenated js file is also committed.

**Comment by jburel** [comment]
I see. Missed that

**Pull request merged**
