### PR TITLE
Rename to omero_figure

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR rename package `figure` to `omero_figure`.

requires https://github.com/openmicroscopy/openmicroscopy/pull/4843 otherwise urls will be using new package name

NOTE: This PR is on top of #168 only for a convenience, otherwise latest and breaking won;t be able to benefit from figure, see https://github.com/openmicroscopy/management_tools/issues/203

---

**Ideally would be to rename repo name after this PR is merged as https://github.com/openmicroscopy/management_tools/issues/203 will need updates**

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
@will-moore @pwalczysko 

```
TypeError: this.template is not a function
$('.new-label-form', this.$el).html(this.template(json));
```

this PR cause https://trello.com/c/2lkbo6x6/181-5-3-0m4-web-deployment-testing

**Comment by will-moore** [comment]
The path that is not found is "figure/static/figure/templates/labels_form_inner_template.html"

**Comment by pwalczysko** [comment]
I am fine on eel merge (i.e. web-dev-merge webserver connecting to eel merge server).
The popup in Figure is as expected also on web-dev-integration connected to cowfish 24064.


But, I have a problem using the export script on cowfish 24064:
```
Traceback (most recent call last):
  File "./script", line 1716, in <module>
    runScript()
  File "./script", line 1703, in runScript
    fileAnnotation = export_figure(conn, scriptParams)
  File "./script", line 1660, in export_figure
    return figExport.buildFigure()
  File "./script", line 664, in buildFigure
    self.createFigure()
  File "./script", line 1363, in createFigure
    "Need to install https://bitbucket.org/rptlab/reportlab")
ImportError: Need to install https://bitbucket.org/rptlab/reportlab
```

**Comment by pwalczysko** [comment]
Now (after fix, rebuild and retest) all works. Ready to merge.

**Comment by will-moore** [comment]
Seems to be working fine locally, once I'd done:
```
$ omero config remove omero.web.apps '"figure"'
$ omero config append omero.web.apps '"omero_figure"'
```
Needs follow up docs PR on new install for sysadmins and developers.
Are we renaming the github repository too?
I think the ```figure/omero_figure/scripts/``` directory can be moved up to ```figure/scripts``` since this doesn't need to be in the Django app. But this can happen in a subsequent PR.

**Comment by will-moore** [comment]
Ah, I see repo rename is already mentioned in description.
This will be good to merge and rename repo soon so we can continue with other PRs that are currently blocked.

**Pull request merged**
