### PR TITLE
1.2.0 release blog post

### PR DESCRIPTION
**Pull request by will-moore**
Release blog post for 1.2.0.
Check link below and follow link to release blog post, scheduled for 16th Nov.
Staged at http://figure.staging.openmicroscopy.org/#releases

### CODE REVIEW

**Comment by gusferguson** [comment]
@will-moore 

All looks good.
Good to merge.

**Comment by jburel** [comment]
@will-moore @gusferguson Until we have the discussion about release process cf e-mail thread,
we won't release figure.
Good to be prepared but no reason to rush

**Comment by hflynn** [comment]
Worth adding a comment that these ROIs are not OMERO ROIs too?

**Comment by will-moore** [comment]
Last commit addresses @pwalczysko's comment on card: https://trello.com/c/CWVSloJC/11-go-over-figure-scenario

**Comment by hflynn** [comment]
Looks good to me

**Comment by pwalczysko** [comment]
2 issues:
  - bullet points are "under the bullet" (see screenshots) 
  - the release date of 16. Nov needs to be updated
screen shot 2015-11-24 at 10 01 15
screen shot 2015-11-24 at 10 01 08

**Comment by hflynn** [comment]
Huh, the bullet points look fine on Safari for me. The date does indeed need updating though.

**Comment by pwalczysko** [comment]
The problem with bullet points https://github.com/ome/figure/pull/125#issuecomment-159214350 noted in Firefox - Chrome is okay as well.

screen shot 2015-11-24 at 11 03 02

**Comment by will-moore** [comment]
Firefox issues fixed and date updated. Re-staged for testing.

**Comment by pwalczysko** [comment]
Retested on Firefox. 

  - bullet point problem -> as expected
  - Date problem -> as expected

Ready to merge.

**Pull request merged**
