### PR TITLE
Luts

### PR DESCRIPTION
**Pull request by will-moore**
This adds LUTs support to OMERO.figure.

To test:
 - click on channel color chooser drop-down and select "Lookup Tables".
 - This will open a dialog showing available LUTs
 - Click a LUT to preview it, then OK
 - Channel button AND slider should have LUT background.
 - This should also work to set the channel LUT when multiple images are selected, even if they have different LUTs/colors for that channel before setting LUT.
 - Export to PDF/TIFF should export images with LUTs applied as in the figure.

screen shot 2016-08-03 at 23 16 22

### CODE REVIEW

**Comment by gusferguson** [comment]
@will-moore 

Tested with https://cowfish.openmicroscopy.org/webmerge/webclient/ user-3 read-only 1 Figure: Test 16-08-04 08:48:09

Selection of colours, LUT and clour picker behave as expected.

Question: @will-moore @jburel 
- using the left panel in the test figure I configured the top channel as blue, the second channel as sepia LUT and the third channel as green
- when I select channel 1 and 3 with 2 deselected, the rendering is as expected - screenshot 1
- but as soon as I select channel 2 (the sepia LUT) it seems to obscure channel 1 but channel 3 is visible - screenshot 2
- if I make channel 2 a normal colour and channel 3 a LUT (grey in this screenshot) both channels 1 and 2 are not visible at all - screenshot 3
- if I put the LUT on channel 1 then I can see all 3 channels - screenshot 4

It looks to me as if selecting an LUT for a channel causes all channels “below” it to be obscured - the graphics app metaphor of this would be - normal colour channels have a “transparent background” but the LUTs don’t.

I am getting the same effect with LUTs with the same image in the main Web app - although on some other images there seems to be a small degree of "show through" below LUTs.

Is this expected?

omero figure 0

omero figure 3

omero figure 4

omero figure 5

**Comment by gusferguson** [comment]
@will-moore @jburel - LUTs in Insight also giving this obscuring effect.

**Comment by jburel** [comment]
same comment here https://github.com/openmicroscopy/openmicroscopy/pull/4764#issuecomment-237485670

**Comment by jburel** [comment]
Alpha is not taken into account when applying LUT (rendering engine), we may need to review that part

**Comment by jburel** [comment]
@gusferguson: https://github.com/openmicroscopy/openmicroscopy/pull/4753/commits/d57c42e21cd1978c480c0ab64306613f7ec2480e fixes the "override" issue mentioned above

**Comment by will-moore** [comment]
To test today's commits:
 - Names of LUTs in picker dialog should not have '.lut', underscores should be replaced by space and name should start with capital letter.
 - If you Add a new image into OMERO.figure, any LUTs saved on that image from Insight/webclient are shown immediately.
 - Layout of channel sliders is fixed (as it was before this PR, instead of start/end labels squashed onto different rows).

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#214](https://ci.openmicroscopy.org/job/FIGURE-merge/214/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/214/consoleText) for more details.
Possible conflicts:
  - PR #152 will-moore 'open with images'
    - static/figure/figure.js
    - static/figure/js/views/modal_views.js
  - PR #158 dominikl 'Label markdown'
    - static/figure/figure.js
  - Upstream changes
    - static/figure/figure.js

**Comment by dominikl** [comment]
The channel color buttons look a bit strange (black vertical line in the center).
screen shot 2016-08-09 at 07 57 49

**Comment by dominikl** [comment]
Ignore the last comment, I guess that's just because I can't get my local server properly setup for lookup tables.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#215](https://ci.openmicroscopy.org/job/FIGURE-merge/215/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/215/consoleText) for more details.
Possible conflicts:
  - PR #152 will-moore 'open with images'
    - static/figure/figure.js
    - static/figure/js/views/modal_views.js
  - PR #158 dominikl 'Label markdown'
    - static/figure/figure.js
  - Upstream changes
    - static/figure/figure.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#216](https://ci.openmicroscopy.org/job/FIGURE-merge/216/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/216/consoleText) for more details.
Possible conflicts:
  - PR #152 will-moore 'open with images'
    - static/figure/figure.js
    - static/figure/js/views/modal_views.js
  - PR #158 dominikl 'Label markdown'
    - static/figure/figure.js
  - Upstream changes
    - static/figure/figure.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#217](https://ci.openmicroscopy.org/job/FIGURE-merge/217/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/217/consoleText) for more details.
Possible conflicts:
  - PR #152 will-moore 'open with images'
    - static/figure/figure.js
    - static/figure/js/views/modal_views.js
  - PR #158 dominikl 'Label markdown'
    - static/figure/figure.js
  - Upstream changes
    - static/figure/figure.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#218](https://ci.openmicroscopy.org/job/FIGURE-merge/218/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/218/consoleText) for more details.
Possible conflicts:
  - PR #158 dominikl 'Label markdown'
    - static/figure/figure.js
  - Upstream changes
    - static/figure/figure.js
    - static/figure/js/views/modal_views.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#219](https://ci.openmicroscopy.org/job/FIGURE-merge/219/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/219/consoleText) for more details.
Possible conflicts:
  - PR #158 dominikl 'Label markdown'
    - static/figure/figure.js
  - Upstream changes
    - static/figure/figure.js
    - static/figure/js/views/modal_views.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#220](https://ci.openmicroscopy.org/job/FIGURE-merge/220/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/220/consoleText) for more details.
Possible conflicts:
  - PR #158 dominikl 'Label markdown'
    - static/figure/figure.js
  - Upstream changes
    - static/figure/figure.js
    - static/figure/js/views/modal_views.js

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [FIGURE-merge#221](https://ci.openmicroscopy.org/job/FIGURE-merge/221/). See the [console output](https://ci.openmicroscopy.org/job/FIGURE-merge/221/consoleText) for more details.
Possible conflicts:
  - PR #158 dominikl 'Label markdown'
    - static/figure/figure.js
  - Upstream changes
    - static/figure/figure.js
    - static/figure/js/views/modal_views.js

**Comment by jburel** [comment]
Having the list of luts hard-coded in 2 different files is far from ideal.

**Comment by will-moore** [comment]
@jburel: The list of LUTs is only hard-coded in one place. Remember that every commit for figure includes the concatenated JavaScript so every change is duplicated.

**Comment by jburel** [comment]
;-) true!!!

**Comment by gusferguson** [comment]
@will-moore 

Tested using https://cowfish.openmicroscopy.org/webmerge/figure/new/ Safari user-3

LUTs behaving as expected.

Good to merge.

**Comment by jburel** [comment]
Thanks merging so we have everything in place

**Pull request merged**
