### PR TITLE
Add shapes to panels

### PR DESCRIPTION
**Pull request by will-moore**
This is the first major part of "ROI support" in OMERO.figure.

To test:
 - Select an image in a figure
 - Choose right "Labels" tab
 - Edit ROIs button should only be enabled when a single Image panel is selected
 - Click Edit ROIs to open dialog
 - A dialog opens that allows you to draw and edit shapes on the panel
 - The 'viewport' should show the same region of the image that was shown of the figure (same zoom, pan etc)
 - Use the toolbar to pick a type of shape, line thickness & colour and then draw on image.
 - Should be able to "tweak" the last-added shape while you are adding (resize, drag etc).
 - Select shapes with the 'select' toolbar option, then resize, drag, change colour, line-width etc.
 - Copy, Paste and Delete options (under the toolbar wrench) should be enabled as appropriate and "just work"
 - Copy-then-Paste on same image should offset the new shape (so it doesn't overlap)
 - Copy, paste & delete should work with standard keyboard shortcuts.
 - Copy and Paste to a different image should be in the exact same location.
 - Once editing is done, click "OK" to close dialog.
 - Shapes should be displayed on figure.
 - Figure Undo/Redo should be updated when shapes are changed

screen shot 2015-08-25 at 21 41 22

screen shot 2015-08-25 at 21 42 23

TODO (next):
 - Multi-select shapes (drag to select)
 - Tooltip or other display of shape coordinates when dragging/resizing
 - Copy and Paste of Rectangle in "crop" dialog
 - Warning when pasting shape that is outside of viewport
 - Copy/paste, colour, thickness editing in right panel without opening dialog?

### CODE REVIEW

**Comment by pwalczysko** [comment]
Sorry, did not manage to have a look today.

**Comment by jburel** [comment]
Readme update should not be done in a separate PR to be cleaner

**Comment by jburel** [comment]
The rois are drawn on a single image. It will be nice to be able to move the dialog so we can see how the roi is displayed in the context of the figure itself.

**Comment by jburel** [comment]
If I move a shape "out of the canvas", I have no way to bring it back.

**Comment by jburel** [comment]
I had few problems when the roi edit is up 
I cannot select other windows or interact with other app, difficult to track but it seems to be related to have the dialog up.

**Comment by will-moore** [comment]
@jburel I can move the README commit to a new PR.
The behaviour of the ROI Edit dialog is the same for all dialogs (non draggable etc). The figure won't update to show you the new Shapes until you hit "OK" and close the dialog, so you won't be able to see the shapes "In the context of the figure itself" even if you could move the dialog.
The issue of dragging shapes out of the image is the same in all shape editors, including Insight. However, it might be useful to have a warning message when you paste a shape that is not in the current viewport. Any other ideas how to handle this?
Can you show me the windows problems "when the roi edit is up"?

**Comment by jburel** [comment]
I do not disagree with the dragging out of canvas.
I got confused when I hit few times paste and the roi "never" shows up in the viewport due to the indentation.

**Comment by jstitlow** [comment]
Hi Will, 
Is there a way for me to help test the ROI editor before the next release?
Looks great so far!
J

**Comment by will-moore** [comment]
@jstitlow Hi Josh - thanks for the offer of help. We need to set up a test server that's accessible from outside Dundee Uni (unless you have a keen sysadmin who can install this branch on a test OMERO server?!). Hopefully we'll have something soon so you can test in good time for the next release.
 Cheers,
  Will.

**Comment by jstitlow** [comment]
Thanks, will talk to our guy about a test server.
Quick question..
Do you know what causes this error when trying to export (PDF or TIFF)?
image

**Comment by will-moore** [comment]
@jstitlow Yes - see https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7441

**Comment by jstitlow** [comment]
Thanks, we got that sorted. 
He will also help set up a virtual machine to use as an OMERO test server. Does it need to have a specific Developer version of OMERO or just the latest release? Also, how do we get the code for the un-released version of .figure?

**Comment by will-moore** [comment]
@jstitlow Any version of OMERO should be fine. To get the latest code for this PR, you can go to the branch https://github.com/will-moore/figure/tree/shape_edit and "Download ZIP", but if you want to update frequently you'll want to clone the github repository, something like:
```
# start in a directory that is on your $PYTHONPATH
$ git clone git@github.com:ome/figure.git
# This created a /figure directory within a dir that is on your $PYTHONPATH - (see install instructions)
$ cd figure
$ git remote add will git@github.com:will-moore/figure.git
$ git fetch will
$ git checkout will/shape_edit
```
NB: in the meantime, you can try the "shape editing" functionality (which is the main part of this PR) by going to the shape-editer page at http://will-moore.github.io/shape-editor-js/ This is what is used in the Edit ROI dialog in figure.

**Comment by will-moore** [comment]
@jburel Now we show a warning if you try to paste a shape that is outside the viewport.

**Comment by pwalczysko** [comment]
Is ``Edit ROIs`` the best name for the button ? Would not ``Draw/Edit`` be more appropriate (in lines with the other items on the ``Labels`` pane like ``Scalebar``

**Comment by pwalczysko** [comment]
The obvious workflow issues come from the fact that the ROI drawing "Viewport" is 
1. large
2. impossible to move
3. covering all the Figure (all the other panels)

With functions like 

screen shot 2015-09-07 at 11 26 04

this becomes quite apparent that you would like to see the other panes as well.

**Comment by pwalczysko** [comment]
Is a relatively thick red line a good default for region properties ? Why not to go for a thin white line as a default (do we have any examples from other softwares defaulting to thick red ? - not IJ) ?

**Comment by pwalczysko** [comment]
This strikes me as an unlucky choice of icon: it is a Copy/Cut/Paste icon, but has a pencil ? in it - rather suggests a text action than the Edit action ? Additionally, this icon should be mentioned in the ``Tip``

**Comment by pwalczysko** [comment]
Ellipse:
Unlike other ROIs, this region is being drawn as far too big in the first place. Compare with drawing a rectangle, you start from ``zero`` size, then drag it larger and larger. Obviously, the ellipse is a bit different, and jumps straight into quite a size as you start to drag the mouse in order to draw it. Especially in zoomed images this becomes apparent. Afterwards, laborious re-selection (with the arrow tool) and resizing to smaller size is necessary.

**Comment by will-moore** [comment]
After discussion with @pwalczysko:
TODO for this PR:
 - "Draw ROI" button (and dialog)?
 - Default colour: white and lineWidth: thin (1 or 2)
 - Use text "Edit" on button instead of wrench
 - Ellipse should scale with regular width/height ratio instead of fixed width

TODO for release:
 - In the "Labels" tab, instead of a single "Draw ROIs" button we also have a summary "3 ROIs" and can bulk edit the colour and line-width and Copy (all) and Paste ROIs here. This means that you can experiment with different sizes without having to open & close the dialog - while seeing the panels in the context of the whole figure.
 - By the zoom slider (and "crop" button) we have a similar looking Copy and Paste buttons that allow you to copy and paste the crop region (without opening the crop dialog). This make it easier to copy a crop region from one panel and paste it as a Rectangle on another panel.
 - In "Draw ROIs" dialog, you can drag to select multiple shapes.
 - Lack of rotation support is not nice - would be good to try and fix this!

**Comment by pwalczysko** [comment]
@will-moore : One more suggestion.
I have just noticed that there is sometimes (not sure what governs this) another Tip displayed (it was also on images with regions already drawn on them).

screen shot 2015-09-07 at 16 20 30

I would suggest to remove this tip (states the obvious, no need for it) and always go for the Copy ROI tip instead in all situations.

**Comment by pwalczysko** [comment]
Re: https://github.com/ome/figure/pull/100#issuecomment-138316407 - yes, Draw ROIs dialog.

**Comment by will-moore** [comment]
@pwalczysko I think those commits address all the TODOs we discussed the other day. Tips are randomly chosen from a short list (see https://github.com/will-moore/figure/commit/22378cf57104bad58f48dd96f1cf0b9954e064fb) but we can update these tips when we have the complete ROI functionality in place.

**Comment by pwalczysko** [comment]
All the TODOs for this PR work as expected.
I will check the Copy Paste actions and the menus on Win7 machine now.

**Comment by pwalczysko** [comment]
Test on Win7 laptop passed.
Nevertheless, the menu symbols are a bit strange on Mac in the new Draw ROIs > Edit dropdown menu.
See screenshots below - 
   1. the symbol for Mac Delete key should be Back Delete (not ``Del``), this is 
screen shot 2015-09-09 at 15 30 41

   2. the shortcut suggestions are not in the same line as the commands in the dropdown and they vanish when the menu item is selected -> unprecedented even in OMERO.figure itself (see the main menu Edit for example)

screen shot 2015-09-09 at 15 28 38
screen shot 2015-09-09 at 15 28 23

**Comment by pwalczysko** [comment]
(note that the point 2. above https://github.com/ome/figure/pull/100#issuecomment-138927997 is valid also for Win7 menu.

**Comment by pwalczysko** [comment]
I think the Edit ROI menu is much better now. No jumping shortcut hints, the cross icon is gone. Lets see what @bramalingam thinks.

**Comment by bramalingam** [comment]
All the actions work as expected. A few outliers discussed (reg: the clipboard for the canvas and the image).

Bug: The display of labels (for any image) does not work if you add them to any of the "outside edges" categories.

**Comment by will-moore** [comment]
@bramalingam I think that should fix the 'outside labels' and 'clipboard' issues. For the clipboard I'm not yet supporting cross-pasting of shapes -> page etc, but at least there is one clipboard now, so the cross-pasting will come later.

Just to summarise what we discussed yesterday: It would be really handy if you could copy shapes (within the 'Draw ROIs' dialog or from a 'Copy ROIs' button) and simply select another panel and paste these shapes using keyboard shortcut. Even more cool would be to select NO panels on the page, then paste one or more Rectangle shapes and have these added as new panels, cropped to the rectangle! 
The same logic could be applied to labels at some point too.
If you copy a crop region, then paste it on another panel via Cmd V, this would crop that panel.
Not sure what would happen if you copy a crop-region, select NO panels on page and paste?? Need more discussion.

**Comment by will-moore** [comment]
@bramalingam One final thing I forgot to mention in description - if you could try rotating a panel, then drawing ROIs on it, and vice versa (draw ROIs then rotate). This workflow is a bit broken, but if you have any ideas for improving it??

**Comment by bramalingam** [comment]
All good here. Good to merge.

Small RFE (Not a regression) : Copy and paste a single image multiple times. Shows some weird paste behaviours  , in terms of patterns (worth a review?)

**Comment by will-moore** [comment]
@jstitlow You can now test this PR and #105 using the demo app http://figure.staging.openmicroscopy.org/demo/#file/1 without having to set up your own server (but can't test figure export there). Would love to hear any feedback you have.

**Comment by jstitlow** [comment]
Works great on my system (OSx in Chrome browser).

**Comment by jstitlow** [comment]
Other ROI features that we would use:
1) Free-hand draw
2) Text box
3) Edit shapes, e.g., change size of arrow heads, make dotted lines

**Comment by will-moore** [comment]
@jstitlow Thanks - dotted lines, free-hand shapes and text box are on my TODO list in that order. I was hoping that I'd chosen a universally acceptable arrow head that users wouldn't need to change?

**Comment by jstitlow** [comment]
I agree, it is a beautiful arrowhead. It can be used alone (as arrowhead)
and with a line (as arrow) to point out different objects. Just mentioning
it to be thorough.

**Comment by jstitlow** [comment]
Hi Will et al., 

I want to download several OMERO.Figure files at once as .pdfs. Can you help me write a script for this?

Many thanks,
Josh

PS- Hopefully we get a chance to chat in Dundee at the OMERO meeting.

**Comment by will-moore** [comment]
@jstitlow Could you open a new issue with a few more details of your use-case. E.g. running script from webclient / commandline / client-side python script? Presumably specifying multiple figures by ID? Downloading a single zip containing multiple PDFs?
See you in Dundee!

**Comment by jstitlow** [comment]
Thanks

*Josh Titlow, Ph.D.*
Postdoctoral Research Associate
Department of Biochemistry
University of Oxford, UK

South Parks Road
Oxford OX1 3QU, UK

(p) (44) (0) 1865 613272 (lab)
(w) http://joshtitlow.wordpress.com/

**Pull request merged**
