### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by will-moore**
This cleans up from the release, switching version to ```1.2.0-dev``` and improving the build process so that less needs to happen for each released.

To test, follow instructions in updated README if needed to get setup, then:
 - ``` $ grunt watch ```
 - Saving js files under ```static/figure/js/``` should trigger "concat" task and saving html templates under ```static/figure/templates``` should trigger "jst" (don't need to change before saving).
```
$ grunt watch
Running "watch" task
Waiting...
>> File "static/figure/js/app.js" changed.
Running "concat:js" (concat) task
File static/figure.js created.

Done, without errors.
Completed in 0.694s at Fri Dec 04 2015 15:07:08 GMT+0000 (GMT) - Waiting...
>> File "static/figure/templates/channel_toggle_template.html" changed.
Running "jst:compile" (jst) task
File static/figure/js/templates.js created.

Done, without errors.
Completed in 0.708s at Fri Dec 04 2015 15:07:17 GMT+0000 (GMT) - Waiting...

```
 - index.html now links directly to concatenated figure.js during development (as it does in release builds) instead of separate js files.
 - Updating version in figure/settings.py and visiting /figure/ in the browser will break browser cache and reload figure.js, templates.js and figure.css

```
[04/Dec/2015 13:36:36] "GET /figure/ HTTP/1.1" 200 47814
[04/Dec/2015 13:36:36] "GET /static/figure/css/figure.css?version=1.2.1 HTTP/1.1" 200 18542
[04/Dec/2015 13:36:36] "GET /static/figure/js/templates.js?version=1.2.1 HTTP/1.1" 200 51307
[04/Dec/2015 13:36:36] "GET /static/figure.js?version=1.2.1 HTTP/1.1" 200 268564
```

### CODE REVIEW

**Comment by pwalczysko** [comment]
If I save ``/figure/static/figure/js]/templates.js`` then the ``grunt concat`` does not start. If I save ```/figure/static/figure/js/app.js`` then it works. If this is expected, then the first part of the test works as expected.

**Comment by pwalczysko** [comment]
All the ``.html`` files in ``/figure/static/figure/templates`` cause the jst task as expected.

**Comment by pwalczysko** [comment]
When I go to ``/figure`` in my locally installed figure, using Firefox (installed it from the git-repo branch which I have cloned locally and have this PR included), I can see that the version under Help > About OMERO.figure has changed as I have changed the version number in ``settings.py`` accordingly.
But: I HAD to restart the web server to see the change (without that the change did not show up in the browser, after just refreshing the browser). Is this expected (the necessity of web restart) ?

**Comment by will-moore** [comment]
@pwalczysko Thanks for testing. Apologies for missing details.
 - templates.js is not "watched" for concat, since this is the product of the ```jst``` task and not a source file.
 - Web restart is needed for the version to be updated in the app.

So everything is working as expected.

**Comment by pwalczysko** [comment]
@will-moore Thanks for clarifying.
Ready to merge.

**Comment by will-moore** [comment]
This seems to be not working on trout for some reason...
https://trout.openmicroscopy.org/merge/figure/
gives 
```
  File "/home/hudson/OMERO.webapps/figure/views.py", line 104, in index
    version = settings.OMERO_FIGURE_VERSION

AttributeError: 'module' object has no attribute 'OMERO_FIGURE_VERSION'
```

**Comment by will-moore** [comment]
On December 4th, build https://ci.openmicroscopy.org/view/OMERO-DEV/job/OMERO-DEV-merge-deploy/178/console had this line
```
Copying '/home/hudson/OMERO.webapps/figure/static/figure-1.2.0.js'
```

But this was missing from the next build https://ci.openmicroscopy.org/view/OMERO-DEV/job/OMERO-DEV-merge-deploy/179/console 3 days later on Dec 7th, presumably because of this PR?

Since then, figure has not worked on eel (as reported today by @pwalczysko).

**Comment by joshmoore** [comment]
The `figure` directory is a symlink:

```
lrwxrwxrwx  1 hudson hudson   42 Oct  8 13:51 figure -> /opt/hudson/workspace/FIGURE-merge-deploy/
```
and the `static` directory doesn't contain anything:
```
[jamoore@ome-c6100-1 static]$ pwd
/opt/hudson/workspace/FIGURE-merge-deploy/static
[jamoore@ome-c6100-1 static]$ ls -ltra
total 12
drwxrwxr-x 7 hudson hudson 4096 Oct  8 13:51 figure
drwxrwxr-x 3 hudson hudson 4096 Dec  7 00:53 .
drwxrwxr-x 8 hudson hudson 4096 Dec 14 04:58 ..
```

Perhaps it's being overwritten?

**Comment by sbesson** [comment]
@will-moore: I might be missing a step but `figure-1.2.0.js` is removed by this PR from what I can see. So isn't it expected that the merge version of OMERO.figure will not copy the `.js` static file as it does not exist?

**Comment by will-moore** [comment]
@sbesson @joshmoore Ooops - thanks, I must have just missed the figure.js from a commit. Fixed now!

**Comment by will-moore** [comment]
@pwalczysko Figure is working again on eel & trout now.

**Comment by will-moore** [comment]
@pwalczysko If you're happy that figure is working on eel now, I think this is good to merge?

**Comment by pwalczysko** [comment]
Yes, it works on eel.
But on trout I get 
```
File "/home/hudson/OMERO.webapps/figure/views.py", line 104, in index
    version = settings.OMERO_FIGURE_VERSION

AttributeError: 'module' object has no attribute 'OMERO_FIGURE_VERSION'
```
after I click onto the ``Figure``.
Is there anything else which needs to happen for trout to work or is it a fault of this PR ?

**Comment by pwalczysko** [comment]
After clarification (thanks @sbesson ) and rebuild of trout merge deploy job, the Figure works as expected on trout as well. 
Ready to merge.

**Comment by sbesson** [comment]
Only minor comment is we could use `1.2.1-dev` rather than `1.2.0-dev` since this translates better the idea this is the development cycle towards version 1.2.1.

**Comment by will-moore** [comment]
@sbesson Updated to 1.2.1-dev as suggested.

**Pull request merged**
