### PR TITLE
Shape export script

### PR DESCRIPTION
**Pull request by will-moore**
This adds shapes to the PDF and TIFF figure export.
NB: script will have to be manually updated each day - please ask if export not enabled.

To test:
 - Draw a bunch of shapes (Line, Arrow, Rectangle, Ellipse) well spread over a number of panels. Panels should have different zoom, pan & rotation. Also add scale bars and 'inner' & 'outer' labels.
 - Export as PDF and TIFF and check that all shapes appear exactly as they are in the web.
 - Shapes should be behind scale bar and other labels.
 - NB: shapes in PDF export are not cropped at the edge of the panel, but if the shape is entirely outside the panel (or centre of Ellipse is outside) then shape should not be added to page.
 - Test multi-page figures - shapes should be correctly positioned on each page.

### CODE REVIEW

**Comment by gusferguson** [comment]
Tested using https://trout.openmicroscopy.org/merge/webclient/ user-3 read-only-1

Draw a bunch of shapes (Line, Arrow, Rectangle, Ellipse) well spread over a number of panels. Panels should have different zoom, pan & rotation. Also add scale bars and 'inner' & 'outer' labels.
- behaves as expected.

Export as PDF and TIFF and check that all shapes appear exactly as they are in the web.
- slight issue with labels placed inside at bottom (left or right) - in PDF and TIFF version they are displaced a little upwards. This is pretty minor - not a blocker. See screenshots 1 and 2 - pink arrow middle right.

NB: shapes in PDF export are not cropped at the edge of the panel, but if the shape is entirely outside the panel (or centre of Ellipse is outside) then shape should not be added to page.
- behaves as expected
- noticed that when exported with images, the TIFF version exports with 3 folders of images - **1_originals**, **2_pre_resampled**, and **3_final** which has images with ROIs. The **2_pre_resampled** folder is not included  with PDF + images export, and the **3_final** folder images are pre-resampled, and don't have the any ROIs on them. See screenshots 3 and 4.

Shapes should be behind scale bar and other labels.
- behaves as expected.

Test multi-page figures - shapes should be correctly positioned on each page.
- behaves as expected

Issue found:

In ROI drawing window - Edit > Copy item in menu works but Paste remains greyed out, even though Cmd-V works for pasting. See screenshot 5.

As a whole, the interaction and ROI drawing works well and is intuitive.

Issue unrelated to ROIs:

If a figure with some panels on it is changed from a single to 2 pages, the size of the panels increase. This  occurs without any ROIs on panels, so unlikely to be related to this PR. Note that it only occurs the first time the number of pages is incremented, not subsequently e,g, if pages reduced to 1 and then incremented again or incremented from 2 to 3. See screenshots 6 and 7. Not a blocker.

omero_figure_-_test_15-09-17_09-07-04

test_15-09-17_09_07_04-3_pdf__page_1_of_2_

finder

finder

safari

omero figure

omero figure

**Comment by sbesson** [comment]
Having restarted Travis after #103 was merged, a couple of long lines need to be split in the script.

**Comment by will-moore** [comment]
@gusferguson Thanks for the testing.
Label positions have never been pixel perfect in the corners. I will improve this at some point but not related to this PR.
The 2_pre_resampled folder is not expected for PDF export (unless you 'set DPI' for any panels). I'm undecided about whether exported companion images should have ROIs drawn on them for TIFF export. Probably not, so I'll fix that.

I've reproduced the 'Paste' option bug and the change in page size when going from 1 to 2 pages, so I'll have a look at fixing them (either in this PR or another).

**Comment by will-moore** [comment]
@gusferguson I've fixed the 2 outstanding issues here:
 - Copy shape (via menu or keyboard shortcut) should enable the Paste menu item.
 - Export of TIFF "with images" should not draw ROIs on the images in folder 3.
If you don't have time to look at this today then no worries (I didn't get around to listing it for standup).

**Comment by gusferguson** [comment]
@will-moore 

Tested using eel merge user-3 read-only-1

Behaves as expected.
Good to merge.

**Pull request merged**
